### ISSUE TITLE
HTMLバリデーションの追加

### ISSUE THREAD

**Issue by cognitom** [aozorahack/aozora-manual#5]
プルリクエストの段階で、テストが走るようにしてはどうでしょうか?

よかったら、この辺と、TravisCIの設定を入れちゃいます。
http://thomasdavis.github.io/w3cjs/

**Comment by takahashim** [comment]
おお、入れて困ることはないと思うので、追加してみていただければ！

**Comment by cognitom** [comment]
ラジャ! 今日はもう遅いので、明日にでも追加しておきます ;-)
